name: stream_app
description: "Live streaming app with RTMP support"
publish_to: 'none'
version: 2.0.0+5

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  apivideo_live_stream:
    path: packages/apivideo_live_stream
  provider: ^6.1.2
  shared_preferences: ^2.3.4
  permission_handler: ^11.3.1
  wakelock_plus: ^1.2.8
  connectivity_plus: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
